#!/usr/bin/env bash
pushd `dirname $0` > /dev/null; BASEDIR=`pwd`; popd > /dev/null

set -ex

DIR=$GOPATH/src/github.com/concourse/docker-image-resource
mkdir -p $DIR

cd $BASEDIR/../..
cp -r . $DIR

cd $DIR
go get cmd/...

OUT=$BASEDIR/../../docker/assets

mkdir -p $OUT

cp Dockerfile $OUT/..
cp assets/* $OUT

BUILT_RESOURCE=$PWD/built-resource

go install github.com/concourse/docker-image-resource/vendor/github.com/onsi/ginkgo/ginkgo

CGO_ENABLED=1 ginkgo -race -r -p

go build -o $OUT/check ./cmd/check/
go build -o $OUT/print-metadata ./cmd/print-metadata/

curl -sSL -O https://get.docker.com/builds/Linux/x86_64/docker-1.12.1.tgz
tar zxf docker-1.12.1.tgz
go build -o ./buildcache github.com/concourse/docker-image-resource/vendor/github.com/tonistiigi/buildcache/cmd/buildcache


go build -o ./ecr-login github.com/concourse/docker-image-resource/vendor/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cmd

cp -a ./* ${BUILT_RESOURCE}/
