#!/usr/bin/env bash
pushd `dirname $0` > /dev/null; BASEDIR=`pwd`; popd > /dev/null

set -ex

DIR=$GOPATH/src/github.com/concourse/docker-image-resource
mkdir -p $DIR

cd $BASEDIR/../..
cp -r . $DIR

cd $DIR
go get cmd/...

OUT=$BASEDIR/../../../docker/assets

mkdir -p $OUT

cp Dockerfile $OUT/..
cp assets/* $OUT

BUILT_RESOURCE=$PWD/built-resource

go install github.com/concourse/docker-image-resource/vendor/github.com/onsi/ginkgo/ginkgo

CGO_ENABLED=1 ginkgo -race -r -p

go build -o $OUT/check ./cmd/check/
